
export const equiposData = [
  { 
    id: 1, 
    hostname: '01SISPE01', 
    ip: '192.168.110.20', 
    sede: 'Paquetería Express', 
    area: 'Tecnología', 
    responsable: 'Stiven Castillo',
    mac: '5A:BF:8E:C8:D7:8D',
    procesador: 'Intel® Core™ i3-12100',
    memoriaRam: '8GB',
    discoDuro: '256GB',
    tipoDisco: 'SSD',
    activo: '5763',
    marca: 'HP',
    referencia: 'ASUS Vivobook 15 IX1607I',
    serial: 'PC-4X93-8Z70QL',
    tipoEquipo: 'Laptop',
    monitor: true,
    monitorInfo: {
      marca: 'Dell',
      activo: '9875',
      serial: 'MON-7H32-9KLMN',
      estado: 'Operativo'
    }
  },
  { 
    id: 2, 
    hostname: '01SISPE02', 
    ip: '192.168.110.239', 
    sede: 'Paquetería Express', 
    area: 'Tecnología', 
    responsable: 'Sebastian Tobar',
    mac: '5A:BF:8E:C8:D7:8E',
    procesador: 'Intel® Core™ i5-11400',
    memoriaRam: '16GB',
    discoDuro: '512GB',
    tipoDisco: 'SSD',
    activo: '5764',
    marca: 'Dell',
    referencia: 'Inspiron 5510',
    serial: 'PC-4X93-8Z70QM',
    tipoEquipo: 'Laptop',
    monitor: false
  },
  { 
    id: 3, 
    hostname: '01SISPT01', 
    ip: '192.168.110.20', 
    sede: 'Paquetería Express', 
    area: 'Tecnología', 
    responsable: 'Stiven Castillo',
    mac: '5A:BF:8E:C8:D7:8F',
    procesador: 'Intel® Core™ i7-12700',
    memoriaRam: '32GB',
    discoDuro: '1TB',
    tipoDisco: 'SSD',
    activo: '5765',
    marca: 'Lenovo',
    referencia: 'ThinkPad T14s',
    serial: 'PC-4X93-8Z70QN',
    tipoEquipo: 'Laptop',
    monitor: true
  },
  { 
    id: 4, 
    hostname: '01SISPE01', 
    ip: '192.168.110.20', 
    sede: 'Paquetería Express', 
    area: 'Tecnología', 
    responsable: 'Stiven Castillo',
    mac: '5A:BF:8E:C8:D7:90',
    procesador: 'Intel® Core™ i5-12500',
    memoriaRam: '16GB',
    discoDuro: '512GB',
    tipoDisco: 'SSD',
    activo: '5766',
    marca: 'HP',
    referencia: 'EliteBook 840 G8',
    serial: 'PC-4X93-8Z70QO',
    tipoEquipo: 'Laptop',
    monitor: false
  },
  { 
    id: 5, 
    hostname: '01SISPE01', 
    ip: '192.168.110.20', 
    sede: 'Paquetería Express', 
    area: 'Tecnología', 
    responsable: 'Stiven Castillo',
    mac: '5A:BF:8E:C8:D7:91',
    procesador: 'Intel® Core™ i3-10100',
    memoriaRam: '8GB',
    discoDuro: '256GB',
    tipoDisco: 'HDD',
    activo: '5767',
    marca: 'Dell',
    referencia: 'Optiplex 3080',
    serial: 'PC-4X93-8Z70QP',
    tipoEquipo: 'Desktop',
    monitor: true
  },
  { 
    id: 6, 
    hostname: '01SISPE01', 
    ip: '192.168.110.20', 
    sede: 'Paquetería Express', 
    area: 'Tecnología', 
    responsable: 'Stiven Castillo',
    mac: '5A:BF:8E:C8:D7:92',
    procesador: 'Intel® Core™ i5-11400',
    memoriaRam: '16GB',
    discoDuro: '512GB',
    tipoDisco: 'SSD',
    activo: '5768',
    marca: 'HP',
    referencia: 'ProDesk 600 G6',
    serial: 'PC-4X93-8Z70QQ',
    tipoEquipo: 'Desktop',
    monitor: true
  },
];

export const chartData = [
  { name: 'Ene', desktop: 40, laptop: 24, servidor: 12 },
  { name: 'Feb', desktop: 42, laptop: 26, servidor: 12 },
  { name: 'Mar', desktop: 45, laptop: 30, servidor: 13 },
  { name: 'Abr', desktop: 50, laptop: 35, servidor: 14 },
  { name: 'May', desktop: 52, laptop: 37, servidor: 15 },
  { name: 'Jun', desktop: 60, laptop: 42, servidor: 19 },
  { name: 'Jul', desktop: 65, laptop: 45, servidor: 20 },
  { name: 'Ago', desktop: 70, laptop: 50, servidor: 22 },
  { name: 'Sep', desktop: 75, laptop: 53, servidor: 24 },
  { name: 'Oct', desktop: 80, laptop: 58, servidor: 25 },
  { name: 'Nov', desktop: 85, laptop: 62, servidor: 28 },
  { name: 'Dic', desktop: 90, laptop: 68, servidor: 30 },
];

export const defaultNewEquipo = {
  hostname: '',
  ip: '',
  sede: 'Paquetería Express',
  area: 'Tecnología',
  responsable: '',
  mac: '',
  procesador: '',
  memoriaRam: '',
  discoDuro: '',
  tipoDisco: 'SSD',
  activo: '',
  marca: '',
  referencia: '',
  serial: '',
  tipoEquipo: 'Laptop',
  monitor: false,
  monitorInfo: {
    marca: '',
    activo: '',
    serial: '',
    estado: 'Operativo'
  }
};
